### ISSUE TITLE
Navigatie

### ISSUE THREAD

**Issue by vasilisvg** [nickrttn/css-to-the-rescue#1]
Ziet er erg tof uit! Paar details nog (ik kan naar onzichtbare items uit het submenu tabben)

**Comment by nickrttn** [comment]
Opgelost door wat javascript toe te voegen. Ik zet nu de tabindex van links uit secondaire navigatie menus op -1 en weer op 0 als de checkbox aangevinkt wordt. Ik weet niet of dit de meest accessible manier is (disabled was bijvoorbeeld ook een optie, maar de links zijn semantisch niet disabled en dat helpt niks bij het verwijderen van focus), maar het werkt goed. Het script gebruikt de `matchMedia` API om te kijken of de huidige breakpoint relevant is voor de JavaScript en werkt alleen wanneer dat het geval is.
