### ISSUE TITLE
Picture with caption

### ISSUE THREAD

**Issue by vasilisvg** [nickrttn/css-to-the-rescue#2]
Dit probleem is complexer: Het plaatje moet _altijd_ helemaal zichtbaar zijn in elke viewport. Dus maximaal `100vh`, en maximaal `100vw`. Bovendien moet je ook altijd kunnen zien dat er een onderschrift is. En dit moet werken met een landscape en een portrait plaatje …
En hier is er iets mis met de aangeleverde HTML. Hier moet je dus wel iets aanpassen (-:

**Comment by nickrttn** [comment]
De `figcaption` staat in de `figure`, zoals het hoort :) Verder heb ik wel overwogen dat een afbeelding altijd mooi zichtbaar moet zijn in elke viewport, liefst met wat context. Daarom heb ik deze een `max-height` van `70vh` gegeven. Ik heb de afbeelding nu ook een `max-width` van `fill` gegeven, zodat hij nooit de beschikbare ruimte overflowt.
